#!/bin/bash

# LOGIN as admin
#source /root/admin-openrc.sh

echo 'enter tenant name'
read -r TENANT_NAME

echo 'enter description'
read -r DESCRIPTION

# ADD tenant
echo ''
keystone tenant-create --name $TENANT_NAME --description "$DESCRIPTION"

# FIND tenant id
echo ''
TENANT_ID=`keystone tenant-list | grep $TENANT_NAME  | awk '{print $2}'`

# CHECK tenant
keystone tenant-get $TENANT_ID > /dev/null 2>&1

if [[ $? -eq 0 ]]; then
	echo "tenant $TENANT_NAME created :-)"
	echo ''
else
	echo ' ALERT ... tenant not created !'
	echo ''
fi

echo ''
echo 'list tenants'
keystone tenant-list | grep $TENANT_NAME
