#!/bin/bash

source /root/creds


# ASK tenant name
echo "insert tenant name"
read TENANT_NAME

# FIND tenant id
TENANT_ID=$(keystone tenant-list | grep -i "${TENANT_NAME}" | awk '{print $2}')

if [[ $TENANT_ID == "" ]]
then
    echo ""
    echo "tenant does not exist"
    exit
fi

# DELETE network
./delete-network "${TENANT_NAME}"

# DELETE tenant
keystone tenant-delete "${TENANT_ID}"

# CHECK
keystone tenant-list | grep -i "${TENANT_NAME}"
if [[ $? -eq 1 ]]; then
	echo "tenant deleted :-)"
fi
